### ISSUE TITLE
A Resource Issue

### ISSUE THREAD

**Issue by swordmeow** [Traneptora/grimoire#100]
I have a suggestion for the maintainers of this tool: remove _healing spirit_.  It is banned by as many tables as I know of, and pretty much follows up "xge is really good, but..." It is so busted that I actually believe it's more of an ethical issue to leave it present in the tool than it would be to remove it.  And of course, this would be a one time thing, not a precedent for future disallowing of spells.

**Comment by Traneptora** [comment]
The Grimoire publishes Rules as Written. If the DM wants to ban Healing Spirit, they should just tell their players that. It's not unethical to report content verbatim just because many DMs don't like it.

Lots of spells are incredibly busted for their level. `Fireball` is actually absurd when you look at it. The creators of the game have decided that some spells will be much more powerful than others because some players like using high-power spells and other players do not. I'm not going to make a balance choice to remove a spell from the Grimoire because many DMs don't like it. Let *them* just say "off limits."

**Comment by swordmeow** [comment]
It's not about being busted for this level. Between you and me there are
obvious ups and downs between some spells, fireball and lightning bolt
being huge because of their names, other spells being less. I can respect
the rules as written approach, but please allow me to make my case here.

You maintain a wonderful resource for the community. Truly. Now that XGE is
published, the balance of 'all published material' has degraded a bit,
which is only to be expected in such a large expansion of player options.
As a moderator of the two foremost d&d homebrew subreddit, as an avid dnd
discussor, but first as a player of Dungeons and Dragons, healing spirit is
unhealthy for the game. It is easy to reduce this to an issue of some DMs
not liking it, but I implore you not to do so. Jeremy Crawford has replied
to one of many tweets saying this "Healing spirit is exceptionally
effective outside combat, and it does have the potential to exceed our
expectations for it. I'll have my eye on it to see if it causes disruption
in actual play, rather than in theoretical situations. If it does, we'll
change it. #DnD <https://twitter.com/hashtag/DnD?src=hash>"

If, to compromise, it could simply be put on hold to see if it is errata'd
or kept the same, possibly only being temporarily removed? Which may be as
little time as a couple weeks to a couple months. Absolutely zero games
will be ruined by your temporary removal of healing spirit, and many games
will be saved. This isn't fireball levels, where fireball mathematically
aligns with a 5th level spell, healing spirit is leagues ahead.

Please, consider it.

**Comment by Traneptora** [comment]
Again, my job is not to make balance decisions. The Grimoire reports rules-as-written. If it's a busted spell, then tell your players not to use it. I am not going to make executive decisions on intentionally not including spells because they're too strong, even if they're *way, way* too strong. I'm not going to make *any* balance decisions on which spells to remove.

That being said, I definitely will update errata when it comes out. 

However, I'm considering adding a feature where sage advice rulings and comments about a spell would be displayed below that spell's page. This would allow non-RAW notes like Jeremy Crawford's tweets or sage-advice columns to clarify how spells work and interact with each other. (Such as being unable to use an unarmed strike with `Booming Blade`).

**Comment by swordmeow** [comment]
Leo,

The spell Healing Spirit has now been nerfed appropriately by Wizards:
https://www.geeknative.com/72126/dd-rule-changes-xanathars-healing-spirit-and-arcane-archers/

Please report the spell Rules as Written.  Cheers.

**Comment by Traneptora** [comment]
Alright, looking into it.

**Comment by Traneptora** [comment]
Errata updated.
